// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY1TRv_bNaDyBZVulPper1PAk07t46U64',
    appId: '1:734906854480:web:32f04b29421a0f9b91b555',
    messagingSenderId: '734906854480',
    projectId: 'italia-news-live',
    authDomain: 'italia-news-live.firebaseapp.com',
    storageBucket: 'italia-news-live.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArKcbhTY2XnnWMyQ3vSZWyx29gvGQ1Tdk',
    appId: '1:734906854480:android:8f76d5cdae0657a491b555',
    messagingSenderId: '734906854480',
    projectId: 'italia-news-live',
    storageBucket: 'italia-news-live.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSL1qwyqwQUFyhE2rFot-PCMQBBXm5oS0',
    appId: '1:734906854480:ios:d090c77f79412aa591b555',
    messagingSenderId: '734906854480',
    projectId: 'italia-news-live',
    storageBucket: 'italia-news-live.appspot.com',
    iosBundleId: 'com.example.globalGazzete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSL1qwyqwQUFyhE2rFot-PCMQBBXm5oS0',
    appId: '1:734906854480:ios:d090c77f79412aa591b555',
    messagingSenderId: '734906854480',
    projectId: 'italia-news-live',
    storageBucket: 'italia-news-live.appspot.com',
    iosBundleId: 'com.example.globalGazzete',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY1TRv_bNaDyBZVulPper1PAk07t46U64',
    appId: '1:734906854480:web:039c68d5a4fa099891b555',
    messagingSenderId: '734906854480',
    projectId: 'italia-news-live',
    authDomain: 'italia-news-live.firebaseapp.com',
    storageBucket: 'italia-news-live.appspot.com',
  );
}
